### ISSUE TITLE
missing data.cioospacicif.ca/erddap

### ISSUE THREAD

**Issue by JessyBarrette** [cioos-siooc/erddap-compliance-runner#1]
I'm not sure why but the compliance checker isn't running the compliance checks on the cioos pacific erddap

**Comment by n-a-t-e** [comment]
https://data.cioospacific.ca/erddap was down at the time this issue was made, it might be related to that

**Comment by JessyBarrette** [comment]
hum I guess we could just rerun the action and see then :)

**Comment by JessyBarrette** [comment]
this is seems to be a one off pacific runner is back
